# -*- coding: utf-8 -*-
"""Lista4_AlgBionf

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ph1UHqoUp_qgdUjc5JoEHDajg0FcZ6Tm
"""

"""Simulações de Monte Carlo são uma classe de algoritmos que usam
números aleatórios para obter resultados numéricos."""

import random
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.axis import Axis
import seaborn as sns

sns.set_style("darkgrid")

x = []
y = []

def plota_grafico(n):
  fig, ax = plt.subplots()
  linha = plt.Circle( ( 0, 0 ), 1, color='black', linewidth=5, fill=False)
  Axis.set_zorder(linha, 20)
  ax.add_artist(linha)
  plt.scatter(x,y)
  plt.title("Gráfico")
  plt.xlabel("Raio")
  plt.ylabel("Raio")
  plt.grid(True)  
  plt.show()

def cria_vetor(n):
  if n < 1:
    print(x)
    print(y)
    print("\n")

  else:
    x.append(random.random())
    y.append(random.random())
    cria_vetor(n-1)

if __name__ == '__main__':
  n = int(input("Digite número de pontos utilizados: "))
  cria_vetor(n)
  plota_grafico(n)
